

```{r}
library(tidyverse) 
library(readxl) 
library(ggpubr) 
library(GGally)
library(performance) 
library(patchwork)
library(rstatix)
```

```{r}
f0_data <- read_excel(path = "C:/Users/Denisa/Documents/5023Y-Summative-2/Data/elegans_offspring.xlsx", sheet = 1, col_names = TRUE, col_types = NULL)
f1_data <- read_excel(path = "C:/Users/Denisa/Documents/5023Y-Summative-2/Data/elegans_offspring.xlsx", sheet = 2, col_names = TRUE, col_types = NULL)
```

```{r}
f0_data$offspring <- as.numeric(f0_data$offspring)
f1_data$offsprings <- as.numeric(f1_data$offsprings)
colnames(f1_data)[4] <- "offspring"

f0_data <- na.omit(f0_data)
f1_data <- na.omit(f1_data)

f0_data$generation <- "f0"
f1_data$generation <- "f1"

colnames(f1_data)[1] <- "rnai"
f1_data <- select(f1_data, -parental_treatment)
f0_data <- select(f0_data, -replicate)

df <- rbind(f0_data, f1_data)

df$treatment <- factor(df$treatment, levels = c("light", "dark"))
df$rnai <- factor(df$rnai, levels = c("raga", "ev"))
df$generation <- factor(df$generation, levels = c("f1", "f0"))
```

```{r}
ggplot(df, aes(x = rnai, y = offspring, fill = treatment)) +
  geom_boxplot(color = "black") +
  facet_wrap(~ generation, ncol = 2) +
  scale_fill_manual(values = c("white", "gray")) +
  labs(x = "RNAi Treatment of f0", y = "Offspring Count") +
  theme_classic()
```

```{r}
ggplot(f0_data, aes(x=rnai, y=offspring, fill=treatment)) +
  geom_boxplot() +
  labs('title' = 'Environmental and genetic treatment on offspring count',
       y = 'Offspring count',
       x = 'RNAi treatment', 
       fill = "Treatment") +
  scale_fill_manual(values = alpha(c("gray", "white"),.3)) 
```

```{r}
f0offspringls1 <- lm(offspring ~ rnai + treatment + rnai + rnai:treatment, data = f0_data)
```

```{r}
performance::check_model(f0offspringls1)
performance::check_model(f0offspringls1, check="homogeneity") 
performance::check_model(f0offspringls1, check=c("normality","qq"))
performance::check_model(f0offspringls1, check="outliers")
```

```{r}
summary(f0offspringls1)
f0offspringmeans2 <- emmeans::emmeans(f0offspringls1, specs = ~treatment)
f0offspringmeans2
f0offspringmeans21 <- emmeans::emmeans(f0offspringls1, specs = ~rnai)
f0offspringmeans21
```

```{r}
f0offspringls1 %>% broom::tidy(conf.int = T) %>% 
  select(-`std.error`) %>% 
  mutate_if(is.numeric, round, 2) %>% 
  kbl(col.names = c("Predictors",
                    "Estimates",
                    "Z-value",
                    "P",
                    "Lower 95% CI",
                    "Upper 95% CI"),
      caption = "f0 generation", 
      booktabs = TRUE) %>% 
  kable_styling(full_width = FALSE, font_size=16, latex_options = c("striped", "hold_position"))
```

```{r}
ggplot(f1_data, aes(x=rnai, y=offspring, fill=treatment)) +
  geom_boxplot() +
  labs('title' = 'Environmental and parental genetic treatment on offspring count',
       y = 'Offspring count',
       x = 'RNAi treatment', 
       fill = "Treatment") +
  scale_fill_manual(values = alpha(c("gray", "white"),.3)) 
```

```{r}
f1offspringls1 <- lm(offspring ~ rnai + treatment + rnai + rnai:treatment, data = f1_data)
```

```{r}
performance::check_model(f1offspringls1)
performance::check_model(f1offspringls1, check="homogeneity") 
performance::check_model(f1offspringls1, check=c("normality","qq"))
performance::check_model(f1offspringls1, check="outliers")
```

```{r}
MASS::boxcox(f1offspringls1)
```

```{r}
f1offspringls1 <- lm(sqrt(offspring) ~ rnai + treatment + rnai + rnai:treatment, data = f1_data)
```

```{r}
performance::check_model(f1offspringls1, check=c("homogeneity", "qq"))
```

```{r}
summary(f1offspringls1)
```

```{r}
f1offspringmeans2 <- emmeans::emmeans(f1offspringls1, specs = ~treatment)
f1offspringmeans2
f1offspringmeans21 <- emmeans::emmeans(f1offspringls1, specs = ~rnai)
f1offspringmeans21
```

```{r}
f1offspringls1 %>% broom::tidy(conf.int = T) %>% 
  select(-`std.error`) %>% 
  mutate_if(is.numeric, round, 2) %>% 
  kbl(col.names = c("Predictors",
                    "Estimates",
                    "Z-value",
                    "P",
                    "Lower 95% CI",
                    "Upper 95% CI"),
      caption = "f1 Generation", 
      booktabs = TRUE) %>% 
  kable_styling(full_width = FALSE, font_size=16, latex_options = c("striped", "hold_position"))
```

